const express=require("express")
const time=require("./node_time_set1")
const Home=require("./HomeRouter")
const All=require("./AllRouter")
const QueryPoints=require("./QueryPointsRouter")
const GetData=require("./GetDataRouter")
const app=express()
app.all('*',function(request,response,next){
    request.header("Access-Control-Allow-Origin", "*")
    next()
})
app.use(express.urlencoded({extended:false}))
app.use(Home)
app.use(All)
app.use(QueryPoints)
GetData()
app.listen(8888,function(){
    console.log("Server running at http://127.0.0.1:8888 when "+time.get_time_now())
})